---
name: Linux GCC

on: [push, workflow_dispatch]

env:
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONFIG_URL: https://github.com/sintef-ocean/conan-configs.git
  DEBIAN_FRONTEND: noninteractive
  TZ: Etc/UTC
jobs:
  conan-with-gcc:
    name: Conan
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        profile: [gcc]
        compiler_version: [12, 13, 14]
        version: ["2025.09.18"]
        build_type: [Debug, Release]
        include:
          - linux: debian:latest
          -
            linux: debian:trixie
            compiler_version: 14
          -
            linux: ubuntu:24.04
            compiler_version: 13
          -
            linux: debian:bookworm
            compiler_version: 12
    container:
      image: ${{ matrix.linux }}
      options: -u 0
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y jq pipx build-essential cmake git gfortran libudev1 pkg-config
          pipx install conan
          echo "/github/home/.local/bin" >> $GITHUB_PATH
      - name: Conan configs
        run: |
          conan remote add sintef ${{ env.CONAN_UPLOAD }}
          echo "package_name=$(conan inspect -f json . | jq .name -r)" >> $GITHUB_ENV
          git config --global --add safe.directory '*'
          conan config install ${{ env.CONFIG_URL }}  --type git -sf conan2.0
          conan config install ${{ env.CONFIG_URL }}  --type git -sf profiles -tf profiles
      - name: Conan create
        run: |
          conan create -s build_type=${{ matrix.build_type }} \
            -o "*:shared=True" \
            -s compiler.version=${{ matrix.compiler_version }} \
            -pr:b=${{ matrix.profile }} -pr:h=${{ matrix.profile }} \
            -b missing -b outdated -b '${{ env.package_name }}*' \
            --version ${{ matrix.version }} --user sintef --channel stable \
            .
      - name: Conan upload
        run: |
          conan upload --confirm -r sintef '${{ env.package_name }}*' --force
